spring:
  application:
    name: Gateway

  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8082
          predicates:
              - Path=/users/**

        - id: reservation_service
          uri: http://localhost:8081
          predicates:
              - Path=/reservations/**
          filters:
            - AuthFilter